SRC = server.c minitalkutils.c client.c\
		
OBJ = $(SRC:.c=.o)

CC = gcc

NAME = fminitalk.a

CFLAGS = -Wall -Werror -Wextra

all: $(NAME)

$(NAME): $(OBJ)
	ar -rcs $(NAME) $(OBJ)

clean:
	rm -f $(OBJ) $(OBJB)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean all